TIP-603: Allow possibility to export the products with all attribute keys possible
akeneo-labs/DataGeneratorBundle pull request #47
Opened 2016-11-08 15:28 UTC by momoss

**Description**

What does this Pull Request do? reference the related issue?

**Definition Of Done**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | N
| Generate fixtures and install     | N
| Generate products and import      | N
| Review and 2 GTM                  | Y
| Tech Doc                          |

2016-11-08 15:37 UTC, momoss commented on AttributeKeyProvider.php
> +class AttributeKeyProvider
This class contains only methods that have been extracted from `Generator/Product/ProductValueRawBuilder.php`

2016-11-08 15:47 UTC, skeleton commented on AttributeKeyProvider.php
> +        $keys = [];
useless initialization

2016-11-08 15:47 UTC, skeleton commented on AttributeKeyProvider.php
> +    public function getAttributeKeys(AttributeInterface $attribute)
quite unreadable IMHO. 70 lines, too much imbrication, no example for each case in description...

2016-11-08 16:28 UTC, BitOne requested changes

2016-11-08 16:28 UTC, BitOne commented on AttributeKeyProvider.php
> +                        $key               = $baseKey . '-' . $locale->getCode() . '-' . $channel->getCode();
bad alignment

2016-11-08 16:28 UTC, BitOne commented on AttributeKeyProvider.php
> +            if ($this->isAttributeKeyValid($keyOptions)) {
It would be better to get the locale from the channel instead of doing validation after having generated the key.

2016-11-08 16:28 UTC, BitOne commented on AttributeKeyProvider.php
> + * @author    Philippe Mossière <philippe.mossiere@akeneo.com>
No accent in the file please.

2016-11-08 16:28 UTC, BitOne commented on AttributeKeyProvider.php
> +    public function getAttributeKeys(AttributeInterface $attribute)
yes, agree.

2016-11-08 16:28 UTC, BitOne commented on AttributeKeyProvider.php
> +                    $updatedKeys[$key]                           = $keyOptions;
A nice illustration of the inconvenient of aligning `=` everywhere ;) The align code is worst than without alignment.

2016-11-08 16:28 UTC, BitOne commented on AttributeKeyProvider.php
> +    private function hasChannelLocale(ChannelInterface $channel, LocaleInterface $locale)
To remove, the locales should come from the channel from the start.

2016-11-08 16:28 UTC, BitOne commented on AttributeKeyProvider.php
> +        return $enabledKeys;
This cannot work: you have absolutely no way to be sure that the keys will always be in the same order if you don't force this order. At least ksort this array.

2016-11-08 16:37 UTC, BitOne commented
Biggest problem with this code: the order of the keys are not guaranteed, meaning the columns can have a different order for different executions. So the files coming from different executions cannot be concatenated.

2016-11-08 17:28 UTC, momoss commented
@BitOne @skeleton the ugly class has been completely rewritten, simplified and speced
Is it better now?

@BitOne the order is guaranteed by `sort($this->headers);`

2016-11-08 17:39 UTC, skeleton approved these changes

2016-11-08 17:59 UTC, BitOne requested changes

2016-11-08 17:59 UTC, BitOne commented on AttributeKeyProvider.php
> +        return $keys;
Still missing the ksort....

2016-11-09 09:27 UTC, SamirBoulil approved these changes

2016-11-09 09:44 UTC, BitOne commented
Okay, thanks for adding the sort.

2016-11-09 09:54 UTC, BitOne approved these changes

2016-11-09 09:55 UTC, merged